// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8JJuqLtg0-6C0AIu9EoPFgTWgJHaHbyE',
    appId: '1:659078460785:web:2525dcfd4e898530d2b2d0',
    messagingSenderId: '659078460785',
    projectId: 'vyaparapp-baa3a',
    authDomain: 'vyaparapp-baa3a.firebaseapp.com',
    storageBucket: 'vyaparapp-baa3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrgA2-54ZVPC1AueGiwFfx_LOqG3a_-Y',
    appId: '1:659078460785:android:5be6dccb80d1193fd2b2d0',
    messagingSenderId: '659078460785',
    projectId: 'vyaparapp-baa3a',
    storageBucket: 'vyaparapp-baa3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5gz0Spr6Ntk5Js8LXlvkfVDVv-bCX5s',
    appId: '1:659078460785:ios:0a75b9d542432b71d2b2d0',
    messagingSenderId: '659078460785',
    projectId: 'vyaparapp-baa3a',
    storageBucket: 'vyaparapp-baa3a.appspot.com',
    iosBundleId: 'com.example.vyaparApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5gz0Spr6Ntk5Js8LXlvkfVDVv-bCX5s',
    appId: '1:659078460785:ios:0a75b9d542432b71d2b2d0',
    messagingSenderId: '659078460785',
    projectId: 'vyaparapp-baa3a',
    storageBucket: 'vyaparapp-baa3a.appspot.com',
    iosBundleId: 'com.example.vyaparApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8JJuqLtg0-6C0AIu9EoPFgTWgJHaHbyE',
    appId: '1:659078460785:web:17bd5c4f3144cb04d2b2d0',
    messagingSenderId: '659078460785',
    projectId: 'vyaparapp-baa3a',
    authDomain: 'vyaparapp-baa3a.firebaseapp.com',
    storageBucket: 'vyaparapp-baa3a.appspot.com',
  );
}
